INTEREST_CATEGORY_ADVENTURE = 'adventure'
INTEREST_CATEGORY_ATTRACTIONS = 'attractions'
INTEREST_CATEGORY_SMARTS_AND_ARTS = 'smarts_and_arts'
INTEREST_CATEGORY_OUT_AND_ABOUT = 'out_and_about'
INTEREST_CATEGORY_NIGHT_LIFE = 'night_life'
INTEREST_CATEGORY_WELLNESS = 'wellness'

INTEREST_CATEGORY_ADVENTURE_LABEL = 'Adventure'
INTEREST_CATEGORY_ATTRACTIONS_LABEL = 'Attractions'
INTEREST_CATEGORY_SMARTS_AND_ARTS_LABEL = 'Smarts & Arts'
INTEREST_CATEGORY_OUT_AND_ABOUT_LABEL = 'Out & About'
INTEREST_CATEGORY_NIGHT_LIFE_LABEL = 'Night Life'
INTEREST_CATEGORY_WELLNESS_LABEL = 'Wellness'

INTEREST_CATEGORY_CHOICES = [
    (INTEREST_CATEGORY_ADVENTURE, INTEREST_CATEGORY_ADVENTURE_LABEL),
    (INTEREST_CATEGORY_ATTRACTIONS, INTEREST_CATEGORY_ATTRACTIONS_LABEL),
    (INTEREST_CATEGORY_SMARTS_AND_ARTS, INTEREST_CATEGORY_SMARTS_AND_ARTS_LABEL),
    (INTEREST_CATEGORY_OUT_AND_ABOUT, INTEREST_CATEGORY_OUT_AND_ABOUT_LABEL),
    (INTEREST_CATEGORY_NIGHT_LIFE, INTEREST_CATEGORY_NIGHT_LIFE_LABEL),
    (INTEREST_CATEGORY_WELLNESS, INTEREST_CATEGORY_WELLNESS_LABEL),
]

INTEREST_CATEGORY_CHOICE_MAPPING = dict(INTEREST_CATEGORY_CHOICES)

INTEREST_AMUSEMENT_PARK = 'amusement_park'
INTEREST_AQUARIUM = 'aquarium'
INTEREST_ART_GALLERY = 'art_gallery'
INTEREST_BAKERY = 'bakery'
INTEREST_BAR = 'bar'
INTEREST_BEAUTY_SALON = 'beauty_salon'
INTEREST_BOOK_STORE = 'book_store'
INTEREST_BOWLING_ALLEY = 'bowling_alley'
INTEREST_CAFE = 'cafe'
INTEREST_CAMPGROUND = 'campground'
INTEREST_CAR_RENTAL = 'car_rental'
INTEREST_CASINO = 'casino'
INTEREST_GYM = 'gym'
INTEREST_LIBRARY = 'library'
INTEREST_MOVIE_THEATER = 'movie_theater'
INTEREST_MUSEUM = 'museum'
INTEREST_NIGHT_CLUB = 'night_club'
INTEREST_PARK = 'park'
INTEREST_RESTAURANT = 'restaurant'
INTEREST_RV_PARK = 'rv_park'
INTEREST_SHOPPING_MALL = 'shopping_mall'
INTEREST_SPA = 'spa'
INTEREST_STADIUM = 'stadium'
INTEREST_ZOO = 'zoo'

INTEREST_AMUSEMENT_PARK_LABEL = 'Amusement Park'
INTEREST_AQUARIUM_LABEL = 'Aquarium'
INTEREST_ART_GALLERY_LABEL = 'Art_gallery'
INTEREST_BAKERY_LABEL = 'Bakery'
INTEREST_BAR_LABEL = 'Bar'
INTEREST_BEAUTY_SALON_LABEL = 'Beauty Salon'
INTEREST_BOOK_STORE_LABEL = 'Book Store'
INTEREST_BOWLING_ALLEY_LABEL = 'Bowling Alley'
INTEREST_CAFE_LABEL = 'Cafe'
INTEREST_CAMPGROUND_LABEL = 'Campground'
INTEREST_CAR_RENTAL_LABEL = 'Car Rental'
INTEREST_CASINO_LABEL = 'Casino'
INTEREST_GYM_LABEL = 'Gym'
INTEREST_LIBRARY_LABEL = 'Library'
INTEREST_MOVIE_THEATER_LABEL = 'Movie Theater'
INTEREST_MUSEUM_LABEL = 'Museum'
INTEREST_NIGHT_CLUB_LABEL = 'Night Club'
INTEREST_PARK_LABEL = 'Park'
INTEREST_RESTAURANT_LABEL = 'Restaurant'
INTEREST_RV_PARK_LABEL = 'RV Park'
INTEREST_SHOPPING_MALL_LABEL = 'Shopping Mall'
INTEREST_SPA_LABEL = 'Spa'
INTEREST_STADIUM_LABEL = 'Stadium'
INTEREST_ZOO_LABEL = 'Zoo'

INTEREST_TYPE_CHOICES = [
    (INTEREST_AMUSEMENT_PARK, INTEREST_AMUSEMENT_PARK_LABEL),
    (INTEREST_AQUARIUM, INTEREST_AQUARIUM_LABEL),
    (INTEREST_ART_GALLERY, INTEREST_ART_GALLERY_LABEL),
    (INTEREST_BAKERY, INTEREST_BAKERY_LABEL),
    (INTEREST_BAR, INTEREST_BAR_LABEL),
    (INTEREST_BEAUTY_SALON, INTEREST_BEAUTY_SALON_LABEL),
    (INTEREST_BOOK_STORE, INTEREST_BOOK_STORE_LABEL),
    (INTEREST_BOWLING_ALLEY, INTEREST_BOWLING_ALLEY_LABEL),
    (INTEREST_CAFE, INTEREST_CAFE_LABEL),
    (INTEREST_CAMPGROUND, INTEREST_CAMPGROUND_LABEL),
    (INTEREST_CAR_RENTAL, INTEREST_CAR_RENTAL_LABEL),
    (INTEREST_CASINO, INTEREST_CASINO_LABEL),
    (INTEREST_GYM, INTEREST_GYM_LABEL),
    (INTEREST_LIBRARY, INTEREST_LIBRARY_LABEL),
    (INTEREST_MOVIE_THEATER, INTEREST_MOVIE_THEATER_LABEL),
    (INTEREST_MUSEUM, INTEREST_MUSEUM_LABEL),
    (INTEREST_NIGHT_CLUB, INTEREST_NIGHT_CLUB_LABEL),
    (INTEREST_PARK, INTEREST_PARK_LABEL),
    (INTEREST_RESTAURANT, INTEREST_RESTAURANT_LABEL),
    (INTEREST_RV_PARK, INTEREST_RV_PARK_LABEL),
    (INTEREST_SHOPPING_MALL, INTEREST_SHOPPING_MALL_LABEL),
    (INTEREST_SPA, INTEREST_SPA_LABEL),
    (INTEREST_STADIUM, INTEREST_STADIUM_LABEL),
    (INTEREST_ZOO, INTEREST_ZOO_LABEL),
]

INTEREST_TYPE_CHOICE_MAPPING = dict(INTEREST_TYPE_CHOICES)
