# Generated by Django 2.1.3 on 2018-12-18 20:27

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('amusement_park', 'Amusement Park'), ('aquarium', 'Aquarium'), ('art_gallery', 'Art_gallery'), ('bakery', 'Bakery'), ('bar', 'Bar'), ('beauty_salon', 'Beauty Salon'), ('book_store', 'Book Store'), ('bowling_alley', 'Bowling Alley'), ('cafe', 'Cafe'), ('campground', 'Campground'), ('car_rental', 'Car Rental'), ('casino', 'Casino'), ('gym', 'Gym'), ('library', 'Library'), ('movie_theater', 'Movie Theater'), ('museum', 'Museum'), ('night_club', 'Night Club'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('rv_park', 'RV Park'), ('shopping_mall', 'Shopping Mall'), ('spa', 'Spa'), ('stadium', 'Stadium'), ('zoo', 'Zoo')], max_length=50)),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('attractions', 'Attractions'), ('smarts_and_arts', 'Smarts & Arts'), ('out_and_about', 'Out & About'), ('night_life', 'Night Life'), ('wellness', 'Wellness')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RendezVousUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_birth', models.DateField()),
                ('interests', models.ManyToManyField(to='users.Interest')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
