# Generated by Django 2.1.3 on 2019-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='type',
            field=models.CharField(choices=[('amusement_park', 'Amusement Park'), ('aquarium', 'Aquarium'), ('art_gallery', 'Art Gallery'), ('bakery', 'Bakery'), ('bar', 'Bar'), ('beauty_salon', 'Beauty Salon'), ('book_store', 'Book Store'), ('bowling_alley', 'Bowling Alley'), ('cafe', 'Cafe'), ('campground', 'Campground'), ('car_rental', 'Car Rental'), ('casino', 'Casino'), ('gym', 'Gym'), ('library', 'Library'), ('movie_theater', 'Movie Theater'), ('museum', 'Museum'), ('night_club', 'Night Club'), ('park', 'Park'), ('restaurant', 'Restaurant'), ('rv_park', 'RV Park'), ('shopping_mall', 'Shopping Mall'), ('spa', 'Spa'), ('stadium', 'Stadium'), ('zoo', 'Zoo')], max_length=50, unique=True),
        ),
    ]
